apiVersion: v2
name: hello-world
description: A Helm chart for deploying the RHOAI Hello World plugin
type: application
version: 0.4.0
appVersion: "0.4.0"
keywords:
  - rhoai
  - openshift-ai
  - plugin
  - hello-world
home: https://github.com/rh-ai-community-plugins/hello-world
sources:
  - https://github.com/rh-ai-community-plugins/hello-world
