apiVersion: v2
name: hello-world-plugin
description: A Helm chart for deploying the RHOAI Hello World Plugin
type: application
version: 0.3.1
appVersion: "0.3.1"
keywords:
  - rhoai
  - openshift-ai
  - plugin
  - hello-world
home: https://github.com/rh-ai-community-plugins/hello-plugin-world
sources:
  - https://github.com/rh-ai-community-plugins/hello-plugin-world
